name: footloose_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  either_dart: ^0.4.0
  equatable: ^2.0.5
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  get_it: ^7.6.0
  http: ^0.13.6
  jwt_decoder: ^2.0.1
  qr_code_scanner: ^1.0.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true